name: time_tracker_flutter_course
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  google_sign_in: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^0.7.4


flutter:
  uses-material-design: true

  assets:
    - assets/images/
